local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>tp', builtin.git_files, {})
vim.keymap.set("n", "<C-P>", builtin.live_grep, {})
vim.keymap.set('n', '<leader>tt', builtin.help_tags, {})
